// Generated by CoffeeScript 1.6.3
(function() {
  var CustomError;

  module.exports = CustomError = (function() {
    function CustomError(props) {
      if (props == null) {
        props = {};
      }
      Error.call(this);
      if (typeof Error.captureStackTrace === 'function') {
        Error.captureStackTrace(this, this.constructor);
      }
      this.name = props.name;
      this.message = props.message;
      this.occurredAt = props.occurredAt;
      this.setPayload(props.payload);
      this.setDefaults();
    }

    CustomError.prototype.setDefaults = function() {
      if (this.name == null) {
        this.name = this.constructor.name;
      }
      if (this.message == null) {
        this.message = "An error has occurred.";
      }
      if (this.occurredAt == null) {
        return this.occurredAt = new Date();
      }
    };

    CustomError.prototype.setPayload = function(payload) {
      if (payload == null) {
        payload = {};
      }
      return this.payload = payload;
    };

    return CustomError;

  })();

}).call(this);

/*
//@ sourceMappingURL=CustomError.map
*/
