// Generated by CoffeeScript 1.6.3
(function() {
  var CustomError;

  CustomError = (function() {
    function CustomError(props) {
      if (props == null) {
        props = {};
      }
      Error.call(this);
      if (typeof Error.captureStackTrace === 'function') {
        Error.captureStackTrace(this, this.constructor);
      }
      this.name = props.name;
      this.message = props.message;
      this.setPayload(props.payload);
      this.setDefaults();
    }

    CustomError.prototype.setDefaults = function() {
      return this.name != null ? this.name : this.name = this.constructor.name;
    };

    CustomError.prototype.setPayload = function(params) {
      return this.payload = this.constructPayload(params);
    };

    CustomError.prototype.constructPayload = function(params) {
      if (params == null) {
        params = {};
      }
      return params;
    };

    return CustomError;

  })();

  module.exports = CustomError;

}).call(this);

/*
//@ sourceMappingURL=CustomError.map
*/
