// Generated by CoffeeScript 1.6.3
(function() {
  exports.CustomError = require('./CustomError');

  exports.NotImplemented = require('./NotImplemented');

}).call(this);

/*
//@ sourceMappingURL=index.map
*/
